name: flet_nodeflow
description: Flet FletNodeflow control
repository: https://github.com/MyGithubAccount/flet-nodeflow/src/flutter/flet_nodeflow
version: 0.1.0
homepage: https://github.com/MyGithubAccount/flet-nodeflow

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flet:
    git:
      url: https://github.com/flet-dev/flet.git
      path: packages/flet
      ref: v0.28.3
  flutter:
    sdk: flutter
  graphview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
